# Generated by Django 3.1.7 on 2021-03-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210307_0516'),
        ('data', '0005_auto_20210307_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.patient'),
        ),
    ]
