# Generated by Django 3.1.7 on 2021-03-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210307_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Access',
        ),
    ]
